name: com_nectrom_metetemplate
description: Mete Template Flutter Uygulaması
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Temel
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  easy_localization: ^3.0.3

  # State Management
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5

  # Dependency Injection
  get_it: ^8.0.3
  injectable: ^2.3.2

  # Networking
  dio: ^5.4.0
  retrofit: ^4.0.1

  # Storage
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^10.0.0-beta.4
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Routing
  auto_route: ^10.1.0+1
  go_router: ^15.1.1

  # Utility
  logger: ^2.0.2
  uuid: ^4.2.2
  dartz: ^0.10.1
  sentry_flutter: ^8.14.2

  # Device
  device_info_plus: ^11.4.0
  battery_plus: ^6.2.1
  internet_connection_checker: ^3.0.1
  permission_handler: ^12.0.0+1
  flutter_local_notifications: ^19.2.1
  vibration: ^3.1.3

  # UI & Media
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.3.1
  image_picker: ^1.0.7

  # JSON & Serialization
  freezed_annotation: ^3.0.0
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_lints: ^5.0.0

  # Code Generation
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^3.0.6
  retrofit_generator: ^9.2.0
  injectable_generator: ^2.4.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/translations/
    - assets/images/
    - assets/animations/
    - assets/icons/
    - assets/placeholders/
    - assets/sounds/
    - assets/videos/
    - assets/configs/
    - assets/fonts/